config/routes.rb
Task1::Application.routes.draw do

  resources :projects do 
    member do
      get "finish_project"
    end
    resources :milestones do
      member do
        get "finish_milestone"
      end
      resources :tasks do
        member do
          get "finish_task"
        end
      end
    end
  end

  resources :users

  root :to => 'projects#index'

 

 

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :name, :start_date, :end_date, :project_id, :status

  belongs_to :project
  
  has_many :tasks

	validates :name, :presence => true
  validate :end_date_less_than_start_date
 
  def end_date_less_than_start_date
   	if self.start_date > self.end_date
  		self.errors.add(:end_date,"End date cannot be less than start date")
  	end  	
  end

  def set_finish
    self.status ="Finished"
  end      
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :desc, :end_date, :name, :start_date, :user_ids, :status

	#validates :name, :presence => true

  has_many :user_projects
  has_many :users, :through => :user_projects

  has_many :milestones

  validates :name, :presence => true
  
 # validates :status, :inclusion => { :in => %w(Start Inprogress Finished),
  #  :message => "%{value} is not a valid status" }
  
  validate :end_date_less_than_start_date

  def set_finish
    self.status="Finished"
  end
  
  def end_date_less_than_start_date
  	if self.start_date > self.end_date
  		self.errors.add(:end_date,"End date cannot be less than start date")
  	end  	
  end  

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :end_date, :milestone_id, :name, :start_date, :status, :user_id

  belongs_to :milestone 
  belongs_to :user 

  #validates :user_id, :numericality => true
  #validates :milestone_id, :numericality => true

  after_create :status_validation
 
  validates :name, :presence => true
    
  validate :end_date_less_than_start_date
  
  def end_date_less_than_start_date
    puts"dddd"
    if self.start_date > self.end_date
       self.errors.add(:end_date,"End date cannot be less than start date")
    end   
  end 
   
    def set_finish
      self.status="Finished"
    end
    
  protected
  def status_validation
    if end_date < Date.today
      self.status = "finished"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :project_ids

  #validates :name, :presence => true

  has_many :user_projects
  has_many :projects, :through => :user_projects
  
  has_many :tasks
  
  #validates :name, :format => { :with => /\A[a-zA-Z]+\z/,
   #u :message => "Only letters allowed" }

end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  attr_accessible :project_id, :user_id
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/milestones_controller.rb
require "pry"
class MilestonesController < ApplicationController

	before_filter :load_projects

	def index
		@milestones = @project.milestones
	end

	def show
		@milestone = @project.milestones.find(params[:id])
		#binding.py
	end

	def new
		#binding.pry
		@milestone = @project.milestones.new
	end

	def create
		@milestone = @project.milestones.new(params[:milestone]) 

		if @milestone.save
			redirect_to project_milestones_path(@project,@milestone),:notice=>"Successfully created"
		else
			render :action=>:new
		end	
	end

	def edit
		@milestone = @project.milestones.find(params[:id])
	end

	def update
		@milestone = @project.milestones.find(params[:id])
		if @milestone.update_attributes(params[:milestone])
			redirect_to project_milestones_path(@project,@milestone),:notice=>"Successfully updated"
		else
			render :action=>:edit
		end	
	end

	def destroy
		@milestone = @project.milestones.find(params[:id])
		@milestone.destroy
		redirect_to project_milestones_path,:notice=>"Successfully Destroy"
	end

	def finish_milestone
		@milestone =  @project.milestones.find(params[:id])
		@milestone.set_finish
		#binding.pry
		if @milestone.save
			redirect_to project_milestones_path(@project),:notice=>"Milestone is finish"
		else
			redirect_to project_milestones_path(@project),:notice=>"Milestone is not finish"
		end
	end

end

def load_projects
		@project = Project.find(params[:project_id])	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_filter :load_user

	def index
		@projects = Project.all
	end
	
	def new
		@project = Project.new
		@users = User.all
	end
	
	def create
		@project = Project.new(params[:project]) 
		if @project.save
			redirect_to projects_path(@project),:notice=>"Successfully created"
		else
			render :action=>:new
		end	

	end
	
	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		params[:project][:user_ids] = [] if params[:project][:user_ids].blank?
		if @project.update_attributes(params[:project])
			redirect_to project_path(@project),:notice=>"Successfully updated"
		else
			#@users = User.all
			render :action=>:edit
		end	
	end
	
	def show
		@project = Project.find(params[:id])

	end
	
	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path,:notice=>"Successfully Destroy"
	end

	def load_user
			@users = User.all
	end

	def finish_project
		@project =  Project.find(params[:id])
		@project.set_finish
		#binding.pry
		if @project.save
			redirect_to projects_path(@project),:notice=>"Project is finish"
		else
			redirect_to projects_path(@project),:notice=>"Milestone is not finish"
		end
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	
	before_filter :load_project_milestones

	def index
		#binding.pry
		@tasks=@milestone.tasks

	end

	def show
		@task=@milestone.tasks.find(params[:id])
	end

	def new
		@task=@milestone.tasks.new
		
	end

	def create
		@task=@milestone.tasks.new(params[:task])
		if @task.save
			redirect_to project_milestone_tasks_path(@project,@milestone,@task),:notice=>"Successfully created"
		else
			render :action=>:new
		end	
	end

	def edit
		@task=@milestone.tasks.find(params[:id])
		#@user=User.all
		#@milestone=Milestone.all	
	end

	def update
		@task=@milestone.tasks.find(params[:id])
		if @task.update_attributes(params[:task])
			redirect_to project_milestone_tasks_path(@project,@milestone,@task),:notice=>"Updated Successfully"
		else
			render :action=>:edit
		end
	end

	def destroy
		@task=@milestone.tasks.find(params[:id])
		@task.destroy
		redirect_to project_milestone_tasks_path(@project,@milestone,@task), :notice=>"Destroyed Successfully"
	end

	def finish_task
		@task =  @milestone.tasks.find(params[:id])
		@task.set_finish
		#binding.pry
		if @task.save
			redirect_to project_milestone_tasks_path(@project,@milestone),:notice=>"Milestone is finish"
		else
			redirect_to project_milestone_tasks_path(@project,@milestone),:notice=>"Milestone is not finish"
		end
	end

	def load_project_milestones
		@user=User.all
		@project=Project.find(params[:project_id])
		@milestone=@project.milestones.find(params[:milestone_id])	
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
		@projects=Project.all
	end

	def create
		@user = User.new(params[:user]) 
		if @user.save
			redirect_to users_path(@user),:notice=>"Successfully created"
		else
			@projects=Project.all		
			render :action=>:new
		end	
	end

	def edit
		@user = User.find(params[:id])
		@projects=Project.all
	end

	def update
		@user = User.find(params[:id])
		params[:user][:project_ids] = [] if params[:user][:project_ids].blank?
		if @user.update_attributes(params[:user])
			redirect_to user_path(@user),:notice=>"Successfully updated"
		else
			@projects=Project.all
			render :action=>:edit
		end	
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path,:notice=>"Successfully Destroy"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projetcs_helper.rb
module ProjetcsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Management System</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="head_bg">
		<h1 class="heading">Project Management System</h1>
		<div class="container_12">
			<div class="grid_4">
				<ul class="menu">
					<li><%= link_to "Project", projects_path %></li>
					<li><%= link_to "User", users_path %></li>
				</ul>
			</div>
	</div>
</div>			

<div class="container_12">
	<div class="container_6 prefix_3 suffix_3">
		<center>
		<%=flash[:notice] %>
		</center>
			<%= yield %>
	</div>
</div>
</body>
</html>

app/views/milestones/_form_milestone.html.erb
<%= form_for([@project,@milestone]) do |m|%>
<% if @milestone.errors.present? %>
<ul class="warning">
	<% @milestone.errors.full_messages.each do |message| %>
	<li><%= message%></li>
	<% end %>
</ul>
<% end %>

<h2><%=hname%> Milestone</h2>

<div class="white_bg">
<table border=1 class="listing">
		<tr><th>Milestone ID</th><td><%= m.text_field :id %></td></tr>
		<tr><th>Milestone Name</th><td><%= m.text_field :name %></td></tr>
		<tr><th>Start Date</th><td><%= m.date_select :start_date %></td></tr>
		<tr><th>End Date</th><td><%= m.date_select :end_date %></td></tr>
		<tr><th>Status</th><td><%= m.select(:status, options_for_select(["Start","Inprocess","Finished"],:selected=>@milestone.status))%></td></tr>		
</table><br>
<center>
<%=	m.submit button %>
</center>
<% end %>
</div>

app/views/milestones/edit.html.erb
<%=render :partial=>"form_milestone",:locals=>{:button=>"Update",:hname=>"Edit"}%>

app/views/milestones/home.html.erb
welcome to the home page of <%= link_to "Milestone", milestone_path %>.

app/views/milestones/index.html.erb
<h1> Milestone Listing</h1>
<hr>
<div class="white_bg">
<table border=1 class="listing">
	<thead>
		<tr>
			<th>Milestone ID</th>
			<th>Milestone Name</th>
			<th>Milestone Status</th>
			<th>Manage</th>
			<th>Task</th>
		</tr>		
	</thead>
	<tbody>
		<% @milestones.each do |m| %>
			<tr>
				<td><%= m.id%></td>
				<td><%= m.name%></td>
				<td><%= m.status%></td>
				<td><%=link_to "Show",project_milestone_path(@project,m)%>
					<%=link_to "Edit",edit_project_milestone_path(@project,m)%>	
					<%=link_to "Delete",project_milestone_path(@project,m), :method=>'delete'%>
					<%if m.status!="Finished"%>
						<%=link_to "Finish",finish_milestone_project_milestone_path(@project,m)%>	
					<%end%>
					</td>
					<td><%=link_to "Task",project_milestone_tasks_path(@project,m)%></td>
			</tr>	
		<% end %>
	</tbody>
</table>
<br>
<%=link_to "New Milestone",new_project_milestone_path(@project)%>
</div>

app/views/milestones/new.html.erb
<%=render :partial=>"form_milestone",:locals=>{:button=>"Save",:hname=>"New"}%>

app/views/milestones/show.html.erb
<h2> Milestone details</h2>

<div class="white_bg">
<table border=1 class="listing" id="show">
	<thead>
		<tr>
			<th>Milestone ID</th>
			<td><%= @milestone.id%></td>
		</tr>
		<tr>
			<th>Milestone Name</th>
			<td><%= @milestone.name%></td>
		</tr>
		<tr>
				<th>Project ID</th>
				<td><%= @milestone.project_id%></td>
			</tr>
		<tr>
			<th>Start Date</th>
			<td><%= @milestone.start_date.strftime("%d/%m/%Y")%></td>
		</tr>
		<tr>
			<th>End Date</th>
			<td><%= @milestone.end_date.strftime("%d/%m/%Y")%></td>
		</tr>
		<tr>
			<th>Status</th>
			<td><%= @milestone.status%></td>
		</tr>
	</thead>
</table>
</div>

app/views/projects/_form_project.html.erb
<%= form_for(@project) do |m| %>
<% if @project.errors.present? %>
<ul class="warning">
<%@project.errors.full_messages.each do |message| %>
<li><%= message%></li>
<% end %>
</ul>
<% end %>

<h2><%=hname%> Project</h2>
<div class="white_bg">
<table border=1 class="listing">
		<tr><th>Project ID</th><td><%= m.text_field :id %></td></tr>
		<tr><th>Project Name</th><td><%= m.text_field :name %></td></tr>
		<tr><th>Description</th><td><%= m.text_area :desc, :size=>"28x4" %></td></tr>	
		<tr><th>Start Date</th><td><%= m.date_select :start_date %></td></tr>
		<tr><th>End Date</th><td><%= m.date_select :end_date %></td></tr>
		<tr><th>Status</th><td><%= m.select(:status, options_for_select(["Start","Inprocess","Finished"],:selected=>@project.status))%></td></tr>
		<tr><th>Users</th>
			<td><%@users.each do |user| %>
				<%= check_box_tag "project[user_ids][]",user.id,@project.users.include?(user) %>
				<%= user.name %><br>
				<% end %>
			</td>
		</tr>
</table><br>
<center>
<%=	m.submit button %>
</center>
<% end %>
</div>

app/views/projects/edit.html.erb
<%=render :partial=>"form_project",:locals=>{:button=>"Update",:hname=>"Edit"}%>

app/views/projects/home.html.erb
It's A home of project

<%= link_to "Projects",projects_index_path %>

app/views/projects/index.html.erb
<h1> Project Listing</h1>
<hr>
<div class="white_bg">
<table border=1 class="listing">
	<thead>
		<tr>
			<th>Project Id</th>
			<th>Project Name</th>
			<th>Status</th>
			<th>Manage</th>
			<th>Milestones</th>
		</tr>		
	</thead>
	<tbody>
		<% @projects.each do |project| %>
			<tr>
				<td><%= project.id%></td>
				<td><%= project.name%></td>
				<td><%= project.status%></td>
				<td>
					<%=link_to "Show",project_path(project)%>
					<%=link_to "Edit",edit_project_path(project)%>
					<%=link_to "Delete",project_path(project),:method=>"delete"%>
					<%if project.status!="Finished"%>
						<%=link_to "Finish", finish_project_project_path(project)%>
					<%end%>
				</td>
				<td><%=link_to "Milestone",project_milestones_path(project)%></td>
			</tr>	
		<% end %>
	</tbody>
</table>			
<br>
<%= link_to "New Project",new_project_path %>
</div>

app/views/projects/new.html.erb
<%=render :partial=>"form_project",:locals=>{:button=>"Save",:hname=>"New"}%>

app/views/projects/show.html.erb
<h2>Project details</h2>
<div class="white_bg">
<table border=1 class="listing" id="show">
	<thead>
		<tr>
			<th>Project ID</th>
			<td><%= @project.id%></td>
		</tr>
		<tr>
			<th>Project Name</th>
			<td><%= @project.name%></td>
		</tr>
		<tr>
			<th>Description</th>
			<td><%= @project.desc%></td>
		</tr>
		<tr>	
			<th>Start Date</th>
			<td><%= @project.start_date.strftime("%d/%m/%Y")%></td>		
		</tr>
		<tr>
			<th>End Date</th>
			<td><%= @project.end_date.strftime("%d/%m/%Y")%></td>
		</tr>
		<tr>
			<th>Users Associated</th>
			<ul>
			<td><%@project.users.each do |us| %>
				<li>
					<%= us.name %><br></li>
				<% end %>
			</ul>
			</td>
		</tr>				
	</thead>
</table>
</div>

app/views/tasks/_form_task.html.erb
<%= form_for([@project,@milestone,@task]) do |t| %>
<% if @task.errors.present? %>
<ul class="warning">
	<% @task.errors.full_messages.each do |message| %>
	<li><%= message%></li>
	<% end %>
</ul>
<% end %>

<h2><%=hname%> Task</h2>
<div class="white_bg">
<table border=1 class="listing">
		<tr><th>Task ID</th><td><%= t.text_field :id %></td></tr>
		<tr><th>Task Name</th><td><%= t.text_field :name %></td></tr>
		<tr><th>User ID</th><td><%= t.select(:user_id, @user.collect{|u|[u.name,u.id]})%></td></tr>
		<tr><th>Start Date</th><td><%= t.date_select :start_date %></td></tr>
		<tr><th>End Date</th><td><%= t.date_select :end_date %></td></tr>
		<tr><th>Status</th><td><%= t.select(:status, options_for_select(["Start","Inprocess","Finished"], :selected=>@task.status))%></td></tr>		
</table><br>
<center>
<%=	t.submit button %>
</center>
<% end %>
</div>

app/views/tasks/edit.html.erb
<%=render :partial=>"form_task",:locals=>{:button=>"Update",:hname=>"Edit"}%>

app/views/tasks/index.html.erb
<h1> Task Listing</h1>
<hr>
<div class="white_bg">
<table border=1 class="listing"%>
	<thead>
		<tr>
			<th>Task ID</th>
			<th>Task Name</th>
			<th>Task Status</th>
			<th>Manage</th>
		</tr>		
	</thead>
	<tbody>
		<% @tasks.each do |t| %>
			<tr>
				<td><%= t.id%></td>
				<td><%= t.name%></td>
				<td><%= t.status%></td>				
				<td><%=link_to "Show",project_milestone_task_path(@project,@milestone,t)%>
					<%= link_to "Edit", edit_project_milestone_task_path(@project,@milestone,t)%>
					<%= link_to "Delete",project_milestone_task_path(@project,@milestone,t), :method=>"delete"%>
					<%if t.status!="Finished"%>
						<%= link_to "Finish",finish_task_project_milestone_task_path(@project,@milestone,t)%>
					<%end%></td>
			</tr>	
		<% end %>
	</tbody>
</table>
<br>
<%= link_to "Add New Task", new_project_milestone_task_path(@project,@milestone)%>
</div>

app/views/tasks/new.html.erb
<%=render :partial=>"form_task",:locals=>{:button=>"Save",:hname=>"New"}%>

app/views/tasks/show.html.erb
	<h2> Task details</h2>
	<div class="white_bg">
	<table border=1 class="listing" id="show">
	<thead>
		<tr>
			<th>Task ID</th>
			<td><%= @task.id%></td>
		</tr>
		<tr>
			<th>Task Name</th>
			<td><%= @task.name%></td>
		</tr>
		<tr>
			<th>Milestone ID</th>
			<td><%= Milestone.find(@task.milestone_id)[:name]%></td>
		</tr>
		<tr>
			<th>User ID</th>
			<td><%= @task.user_id%></td>
		</tr>
		<tr>
			<th>Start Date</th>	
			<td><%= @task.start_date.strftime("%d/%m/%Y")%></td>	
		</tr>
		<tr>
			<th>End Date</th>
			<td><%= @task.end_date.strftime("%d/%m/%Y")%></td>
		</tr>
		<tr>
			<th>Status</th>
			<td><%= @task.status%></td>	
		</tr>		
	</thead>
	</table>
</div>

app/views/users/_form_user.html.erb
<%= form_for(@user) do |u|%>
<% if @user.errors.present? %>
<ul class="warning">
	<% @user.errors.full_messages.each do |message| %>
	<li><%= message%></li>
	<% end %>
</ul>
<% end %>

<h2><%=hname%> User</h2>
<div class="white_bg">
<table border=1 class="listing">
		<tr><th>User ID</th><td><%= u.text_field :id %></td></tr>
		<tr><th>User Name</th><td><%= u.text_field :name %></td></tr>
		<tr><th>Project Name</th>
			<td><%@projects.each do |project| %>
				<%= check_box_tag "user[project_ids][]",project.id,@user.projects.include?(project) %>
				<%= project.name %><br>
				<% end %>
			</td>
		</tr>
</table><br>
<center>
<%=	u.submit button %>
</center>
<% end %>
</div>

app/views/users/edit.html.erb
<%=render :partial=>"form_user",:locals=>{:button=>"Update",:hname=>"Edit"}%>

app/views/users/index.html.erb
<h1> User Listing</h1>
<hr>
<div class="white_bg">
<table border=1 class="listing">
	<thead>
		<tr>
			<th>User ID</th>
			<th>User Name</th>
			<th>Manage</th>
		</tr>		
	</thead>
	<tbody>
		<% @users.each do |u| %>
			<tr>
				<td><%= u.id%></td>
				<td><%= u.name%></td>
				<td><%=link_to "Show",user_path(u)%>
					<%=link_to "Edit",edit_user_path(u)%>	
					<%=link_to "Delete",user_path(u), :method=>"delete"%></td>
			</tr>	
		<% end %>
	</tbody>
</table>
<br>
<%=link_to "New User",new_user_path%>
</div>

app/views/users/new.html.erb
<%=render :partial=>"form_user",:locals=>{:button=>"Save",:hname=>"New"}%>

app/views/users/show.html.erb
<h2> User details</h2>
<div class="white_bg">
<table border=1 class="listing" id="show">
	<thead>
		<tr>
			<th>User ID</th>
			<td><%= @user.id%></td>
		<tr>
		</tr>
			<th>User Name</th>
			<td><%= @user.name%></td>
		</tr>
		<tr>
			<th>Projects Associated</th>
			<ul>
			<td><%@user.projects.each do |us| %>
				<li>
					<%= us.name %><br></li>
				<% end %>
			</ul>
			</td>
		</tr>		
	</thead>
</table>
</div>